export const orders = [
  {
    id: '#P4E-1259',
    customer: 'Jane D.',
    type: 'Delivery',
    status: 'New',
    time: '5 mins ago',
    items: 3,
    due: '15 min',
    details: '1x Pepperoni Pizza, 1x Garlic Knots, 1x Coke',
    notes: 'Extra cheese, no onions.',
    paid: true,
  },
  {
    id: '#P4E-1258',
    customer: 'Mike R.',
    type: 'Pickup',
    status: 'New',
    time: '8 mins ago',
    items: 2,
    due: '12 min',
  },
  {
    id: '#P4E-1257',
    customer: 'Sarah L.',
    type: 'Delivery',
    status: 'New',
    time: '10 mins ago',
    items: 5,
    due: '20 min',
  },
  {
    id: '#P4E-1256',
    customer: 'Tom H.',
    type: 'Pickup',
    status: 'In Progress',
    time: 'Cooking: 5/15 min',
  },
  {
    id: '#P4E-1255',
    customer: 'Chris P.',
    type: 'Delivery',
    status: 'In Progress',
    time: 'Cooking: 12/20 min',
  },
  {
    id: '#P4E-1254',
    customer: 'Anna K.',
    type: 'Pickup',
    status: 'Ready',
    time: 'Ready for 3 min',
  },
  {
    id: '#P4E-1253',
    customer: 'David B.',
    type: 'Delivery',
    status: 'New',
    time: '12 mins ago',
    items: 1,
    due: '18 min',
    details: '1x Veggie Pizza',
    notes: 'No mushrooms.',
    paid: true,
  },
  {
    id: '#P4E-1252',
    customer: 'Emily S.',
    type: 'Pickup',
    status: 'In Progress',
    time: 'Cooking: 2/10 min',
  },
  {
    id: '#P4E-1251',
    customer: 'Michael J.',
    type: 'Delivery',
    status: 'Ready',
    time: 'Ready for 5 min',
  },
];
